api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('save_order', views.save_order, name='save_order'),
    path('open_box', views.open_box, name='open_box'),
]

selfstorage/urls.py
from users import views as userviews
from storages import views as storagesviews
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from storages.views import view_storages


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', storagesviews.view_index, name='index'),
    path('api/', include('api.urls')),
    path('account/', userviews.lk, name='account'),
    path('boxes/', view_storages, name='boxes'),
    path('faq/', TemplateView.as_view(template_name='faq.html'), name='faq'),
    path('pay/', TemplateView.as_view(template_name='pay.html'), name='pay'),
    path('users/', include('users.urls')),
    path('register/', userviews.register, name='register'),
    path('signin/', userviews.signin, name='signin'),
    path('manager/', include('storages.urls')),
    path('order_details/<product_number>/', storagesviews.order_details, name='order_details'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storages/urls.py
from django.urls import path

from . import views

app_name = 'storages'

urlpatterns = [
    path('', views.view_manager_menu, name='manager_menu'),
    path('expired_orders/', views.view_expired_orders, name='expired_orders'),
    path('orders/', views.view_orders, name='view_orders'),
]

storages/models.py
from datetime import date, datetime
from django.db import models
from django.db.models import F, Min, Count, Q, Sum
from django.utils import timezone


class StorageQuerySet(models.QuerySet):
    def with_min_price(self):
        return self.annotate(
            min_price=Min('boxes__rental_price')
        )

    def with_availability(self):
        return self.annotate(
            empty_boxes=Count(
                'boxes',
                filter=Q(boxes__order=None),
                distinct=True
            ),
            all_boxes=Count(
                'boxes',
                distinct=True
            )
        )


class Storage(models.Model):
    city = models.CharField('город', max_length=50)
    address = models.CharField('адрес', max_length=100)
    temperature = models.SmallIntegerField('температура')
    ceiling_height = models.FloatField('Высота в метрах')
    feature = models.CharField('особенность', max_length=50, blank=True)
    contacts = models.CharField('Контакты', max_length=50, blank=True)
    description = models.TextField('Описание', blank=True)
    driving_directions = models.TextField('Схема проезда', blank=True)

    objects = StorageQuerySet.as_manager()

    class Meta:
        verbose_name = 'Склад'
        verbose_name_plural = 'Склады'

    def __str__(self):
        return f'{self.city}, {self.address}'


class StorageImage(models.Model):
    order = models.PositiveIntegerField(default=1, verbose_name='Порядок')
    image = models.ImageField(verbose_name='Изображение')
    storage = models.ForeignKey(
        Storage,
        on_delete=models.CASCADE,
        related_name='images',
        verbose_name='склад'
    )

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'{self.order} {self.storage}'


class BoxQuerySet(models.QuerySet):
    def with_area(self):
        return self.annotate(
            area=F('width') * F('length')
        )

    def to_3(self):
        return self.annotate(
            area=F('width') * F('length')
        ).filter(
            area__lte=3
        )

    def to_10(self):
        return self.annotate(
            area=F('width') * F('length')
        ).filter(
            area__lte=10
        )

    def from_10(self):
        return self.annotate(
            area=F('width') * F('length')
        ).filter(
            area__gte=10
        )


class OrderQuerySet(models.QuerySet):
    def with_cost(self):
        return self.annotate(
            cost=Sum('boxes__rental_price')
        )

    def expired(self):
        current_date = datetime.now()
        return self.filter(end_current_rent__lt=current_date)

    def with_remaining_term(self):
        return self.annotate(
            remaining_term=(F('end_current_rent') - date.today())
        )


class Order(models.Model):
    UNPROCCESSED = 'UN'
    ON_THE_WAY = 'OTW'
    DONE = 'D'
    STATUSES = (
        (UNPROCCESSED, 'Необработан'),
        (ON_THE_WAY, 'В пути'),
        (DONE, 'Завершён'),
    )
    renter = models.ForeignKey(
        'users.User',
        verbose_name='заказчик',
        related_name='orders',
        on_delete=models.CASCADE
    )
    need_delivery = models.BooleanField('нужна доставка?', default=False)
    address = models.CharField('адрес', max_length=100, blank=True)
    status = models.CharField(
        'статус',
        max_length=10,
        choices=STATUSES,
        default=UNPROCCESSED,
        db_index=True
    )
    created_at = models.DateTimeField(
        'дата и время заказа',
        default=timezone.now,
        db_index=True
    )
    start_current_rent = models.DateField(
        'Начало текущей аренды',
        default=timezone.now,
    )
    end_current_rent = models.DateField(
        'Конец текущей аренды',
    )

    objects = OrderQuerySet.as_manager()

    @property
    def get_delay(self):
        return (self.end_current_rent - date.today()).total_seconds() // 86400

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.renter} {self.address}'


class Box(models.Model):
    storage = models.ForeignKey(
        Storage,
        verbose_name='Склад',
        related_name='boxes',
        on_delete=models.CASCADE
    )
    number = models.CharField(
        'номер',
        max_length=20,
        unique=True,
    )
    floor = models.SmallIntegerField('этаж')
    width = models.FloatField('ширина')
    length = models.FloatField('длина')
    height = models.FloatField('высота')

    rental_price = models.PositiveSmallIntegerField('Стоимость')
    order = models.ForeignKey(
        Order,
        verbose_name='Заказ',
        related_name='boxes',
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    objects = BoxQuerySet.as_manager()

    class Meta:
        verbose_name = 'бокс'
        verbose_name_plural = 'боксы'

    def __str__(self):
        return self.number

storages/views.py
from datetime import date, timedelta

from django.shortcuts import render
from django.contrib.auth.decorators import user_passes_test

from .models import Order, Box, Storage
from geolocation.views import get_nearest_storage
from users.forms import UserCreationForm


def is_manager(user):
    return user.is_staff


@user_passes_test(is_manager, login_url='signin')
def view_orders(request):
    orders = Order.objects.exclude(status='D') \
                          .filter(need_delivery=True) \
                          .with_cost() \
                          .select_related('renter')

    return render(
        request,
        template_name='order_items.html',
        context={'order_items': orders}
    )


@user_passes_test(is_manager, login_url='signin')
def view_expired_orders(request):
    orders = Order.objects.expired() \
                          .prefetch_related('boxes') \
                          .select_related('renter') \
                          .order_by('end_current_rent')
    for order in orders:
        order.number_of_boxes = [box.number for box in order.boxes.all()]
    return render(
        request,
        template_name='expired_orders.html',
        context={'order_items': orders}
    )


@user_passes_test(is_manager, login_url='signin')
def view_manager_menu(request):
    return render(request, template_name='manager.html')


def order_details(request, product_number):
    if not request.user.is_authenticated:
        form = UserCreationForm()
        return render(
            request,
            "login.html",
            context={'form': form}
        )
    box = Box.objects.with_area().filter(number=product_number)[0]
    if request.GET.get('prolong'):
        start_current_rent = box.order.start_current_rent
        end_current_rent = box.order.end_current_rent + timedelta(days=30)
    else:
        start_current_rent = date.today()
        end_current_rent = start_current_rent + timedelta(days=30)
    return render(
        request,
        template_name='order_details.html',
        context={
            'box': box,
            'start_rent': start_current_rent,
            'end_rent': end_current_rent
        }
    )


def view_storages(request):
    storages = Storage.objects.with_min_price() \
                              .with_availability() \
                              .all()

    return render(
        request,
        template_name='boxes.html',
        context={'storages': storages}
    )


def view_index(request):
    nearest_storage = get_nearest_storage(request)
    nearest_storage = Storage.objects.with_min_price() \
                             .with_availability() \
                             .filter(pk=nearest_storage.pk)[0]
    return render(
        request,
        template_name='index.html',
        context={'nearest_storage': nearest_storage}
    )

storages/templates/base_storages_page.html
<!doctype html>{% load static %}
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="icon" href="{% static 'icon.png' %}" type="image/x-icon">

  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>
<body>

  {% block header_nav %}
  {% endblock header_nav %}

  {% block content %}{% endblock %}

</body>
</html>

storages/templates/expired_orders.html
{% extends 'base_storages_page.html' %}


{% block title %}Просроченные заказы{% endblock %}

{% block content %}
  <center>
    <h2>Просроченные заказы</h2>
  </center>

  <hr/>
  <br/>
  <br/>
  <div class="container">
   <table class="table table-responsive">
    <tr>
      <th>ID заказа</th>
      <th>Клиент</th>
      <th> Номер телефона </th>
      <th>Номер бокса</th>
      <th>Срок задержки оплаты</th>
      <th>Ссылка на админку</th>
    </tr>

    {% for item in order_items %}
      <tr>
        <td>{{ item.id }}</td>
        <td>{{ item.renter }}</td>
        <td>{{ item.renter.phonenumber }}</td>
        <td>
        {% for box in item.number_of_boxes %}
          {{ box }}
        {% endfor %}
        </td>
        <td>{{item.get_delay }}</td>
        <td><a href="{% url 'admin:storages_order_change' object_id=item.id %}?next={{ request.get_full_path|urlencode:'' }}">Редактировать</a></td>
      </tr>
    {% endfor %}
   </table>
  </div>
{% endblock %}

storages/templates/manager.html
<!doctype html>{% load static %}
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="icon" href="{% static 'icon.png' %}" type="image/x-icon">

  <title>Меню</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'Style.css' %}">
</head>
<body>
    <div class="modal-body d-flex justify-content-center align-items-center">
            {% csrf_token %}
            <h1 class="modal-title text-center fw-bold mb-3">Меню</h1>
            <p align="center"><a class="btn border-8 py-3 px-5 w-100 text-white fs_24 SelfStorage__bg_orange SelfStorage__btn2_orange" href="{% url 'storages:view_orders' %}">Необработанные Заказы</a></p>
            <p align="center"><a class="btn border-8 py-3 px-5 w-100 text-white fs_24 SelfStorage__bg_orange SelfStorage__btn2_orange" href="{% url 'storages:expired_orders' %}">Просроченные Заказы</a></p>
    </div>
</body>
</html>

storages/templates/order_details.html
{% extends 'base.html' %}
{% load static %}

{% block script%}
<script src="https://3dsec.sberbank.ru/payment/docsite/assets/js/ipay.js"></script>
<script>
    var ipay = new IPAY({api_token: 'YRF3C5RFICWISEWFR6GJ'});
</script>
<script>
    function showSuccessfulPurchase(order) {
        order.box = '{{box}}'
        order.start_rent = '{{start_rent|date:"Y-m-d"}}'
        order.end_rent = '{{end_rent|date:"Y-m-d"}}'
        let data = JSON.stringify(order);
        var xhr = new XMLHttpRequest();
        xhr.open("POST", "{% url 'api:save_order' %}", true);
        xhr.send(data);
        xhr.onload = function() {
        let responseObj = xhr.response;
        // TODO редирект на главную
        };
    };
</script>
{% endblock %}

{% block content %}
<main class="container mt-header">
<center>
    <h2>Проверьте детали вашего заказа</h2>
</center>
<div class="container">
    <p>Склад: {{ box.storage }}</p>
    <p>Номер: {{ box.number }}</p>
    <p>Этаж: {{ box.floor }}</p>
    <p>Площадь: {{ box.area }}</p>
    <p>Начало аренды: {{ start_rent }}</p>
    <p>Конец аренды: {{ end_rent }}</p>
    <div class="d-flex flex-column align-items-center align-items-lg-start">
        <a onclick="ipayCheckout({
            amount: Number('{{ box.rental_price }}'),
            currency:'RUB',
            order_number:'',
            description: 'Аренда помещения {{ box.number }} на складе {{ box.storage }}'},
            function(order) { showSuccessfulPurchase(order) },
            function(order) { showFailurefulPurchase(order) })"
        
            role="button" class="btn w-75 fs_24 px-5 py-3 text-white border-8 SelfStorage__bg_green SelfStorage__btn2_green mb-3">Арендовать бокс</a>
    </div>
</main>
{% endblock %}

storages/templates/order_items.html
{% extends 'base_storages_page.html' %}


{% block title %}Необработанные заказы{% endblock %}

{% block content %}
  <center>
    <h2>Необработанные заказы</h2>
  </center>

  <hr/>
  <br/>
  <br/>
  <div class="container">
   <table class="table table-responsive">
    <tr>
      <th>ID заказа</th>
      <th>Статус</th>
      <th>Клиент</th>
      <th> Номер телефона </th>
      <th>Адрес доставки</th>
      <th>Стоимость</th>
      <th>Ссылка на админку</th>
    </tr>

    {% for item in order_items %}
      <tr>
        <td>{{ item.id }}</td>
        <td>{{ item.get_status_display }}</td>
        <td>{{ item.renter }}</td>
        <td>{{ item.renter.phonenumber }}</td>
        <td>{{ item.address }}</td>
        <td>{{ item.cost }}</td>
        <td><a href="{% url 'admin:storages_order_change' object_id=item.id %}?next={{ request.get_full_path|urlencode:'' }}">Редактировать</a></td>
      </tr>
    {% endfor %}
   </table>
  </div>
{% endblock %}