api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('save_order', views.save_order, name='save_order'),
    path('open_box', views.open_box, name='open_box'),
]

selfstorage/urls.py
from users import views as userviews
from storages import views as storagesviews
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from storages.views import view_storages


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', storagesviews.view_index, name='index'),
    path('api/', include('api.urls')),
    path('account/', userviews.lk, name='account'),
    path('boxes/', view_storages, name='boxes'),
    path('faq/', TemplateView.as_view(template_name='faq.html'), name='faq'),
    path('pay/', TemplateView.as_view(template_name='pay.html'), name='pay'),
    path('users/', include('users.urls')),
    path('register/', userviews.register, name='register'),
    path('signin/', userviews.signin, name='signin'),
    path('manager/', include('storages.urls')),
    path('order_details/<product_number>/', storagesviews.order_details, name='order_details'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'Style.css' %}">
	{% block script%}
	{% endblock %}
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
<header class="navbar navbar-expand-xl navbar-light fixed-top bg-white py-5">
	<nav class="container">
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="{% url 'index' %}">
			<img src="{% static 'img/Vector.svg' %}" alt="[]">
			<img src="{% static 'img/SelfStorage.svg' %}" alt="SelfStorage">
		</a>
		<div class="collapse navbar-collapse justify-content-end" id="navbar">
			<ul class="navbar-nav">
				<li class="nav-item me-5">
					<a class="nav-link SelfStorage_black" href="{% url 'index' %}#calculate">Рассчитать стоимость</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link SelfStorage_black" href="{% url 'faq' %}">Правила хранения</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link SelfStorage_black" href="{% url 'boxes' %}">Арендовать бокс</a>
				</li>
				<li class="nav-item d-flex align-items-center">
				{% if user.is_authenticated %}
					<a class="nav-link fw-lighter SelfStorage_green" href="{% url 'account' %}" >{{ user.email }}</a>
					<a class="nav-link fw-lighter SelfStorage_green" href="{% url 'logout' %}" >Выйти</a>
				{% else %}
					<a class="nav-link SelfStorage_green " href="#" data-bs-toggle="modal" data-bs-target="#SignModal">Войти</a>
					<a class="nav-link SelfStorage_green" href="#" data-bs-toggle="modal" data-bs-target="#RegModal" data-bs-dismiss="modal" aria-label="Close">Зарегистрироваться</a>
				{% endif %}
				</li>
				<li class="nav-item d-flex align-items-center">
					<div class="d-flex justify-content-center align-items-center rounded-pill SelfStorage__bg_green me-2" style="height: 36px; width: 36px;">
						<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="white" class="bi bi-telephone-fill" viewBox="0 0 16 16">
							<path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
						</svg>
					</div>
					<b>8 (800) 000-00-00</b>
				</li>
			</ul>
		</div>
	</nav>
</header>

{% block content %}
{% endblock %}

</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% block title %}Авторизация{% endblock %}
{% if user.is_authenticated %}
{% else %}
  <aside class="modal fade" id="RegModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-fullscreen">
      <div class="modal-content">
        <div class="modal-header border-0">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex justify-content-center align-items-center">
          <form class="d-flex flex-column align-items-center" action="/register/" method="post" style="max-width: 420px">
            <h1 class="modal-title text-center fw-bold mb-3">Регистрация</h1>
            <input type="email" required name="EMAIL_CREATE" class="form-control  border-8 mb-4 py-3 px-5 border-0 fs_24 SelfStorage__bg_lightgrey" placeholder="E-mail">
            <input type="password" required name="PASSWORD_CREATE" class="form-control  border-8 mb-4 py-3 px-5 border-0 fs_24 SelfStorage__bg_lightgrey" placeholder="Пароль">
            <input type="password" required name="PASSWORD_CONFIRM" class="form-control  border-8 mb-4 py-3 px-5 border-0 fs_24 SelfStorage__bg_lightgrey" placeholder="Подтверждение пароля">
            <span class="fw-light SelfStorage_grey">Нажимая на кнопку, вы подтверждаете свое <a href="{% static 'consent_to_the_processing_of_personal_data.pdf' %}" target=»_blank» class="SelfStorage_grey">согласие на обработку персональных данных</a></span>
            <button class="btn border-8 py-3 px-5 mt-5 mb-3 w-100 text-white fs_24 SelfStorage__bg_orange SelfStorage__btn2_orange">Зарегистрироваться</button>
            <span>Уже зарегистрированы? <a href="#" class="SelfStorage_orange" data-bs-toggle="modal" data-bs-target="#SignModal" data-bs-dismiss="modal" aria-label="Close">Войти в личный кабинет</a></span>
          </form>
        </div>
      </div>
    </div>
  </aside>
  <div class="modal-body d-flex justify-content-center align-items-center">
      <form class="d-flex flex-column align-items-center" action="/signin/" method="post" style="max-width: 420px">
          {% csrf_token %}
          <h1 class="modal-title text-center fw-bold mb-3">Вход</h1>
          <input type="email" required name="EMAIL" class="form-control  border-8 mb-4 py-3 px-5 border-0 fs_24 SelfStorage__bg_lightgrey" placeholder="E-mail">
          <input type="password" required name="PASSWORD" class="form-control  border-8 mb-4 py-3 px-5 border-0 fs_24 SelfStorage__bg_lightgrey" placeholder="Пароль">
          <a href="#" class="SelfStorage_orange" data-bs-toggle="modal" data-bs-target="#ForgetModal" data-bs-dismiss="modal" aria-label="Close">Забыли пароль?</a>
          <button type="submit" class="btn border-8 py-3 px-5 mt-5 mb-3 w-100 text-white fs_24 SelfStorage__bg_orange SelfStorage__btn2_orange">Войти</button>
          <span>Нет аккаунта?  <a href="#" class="SelfStorage_orange" data-bs-toggle="modal" data-bs-target="#RegModal" data-bs-dismiss="modal" aria-label="Close">Зарегистрируйтесь на сайте</a></span>
      </form>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script>
    var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
    var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
      return new bootstrap.Popover(popoverTriggerEl)
    })
  </script>
{% endif %}
{% endblock %}

templates/my-rent-empty.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main class="container mt-header">
	<div class="row" role="tablist">
		<div class="col-lg-3 d-flex flex-column nav nav-pills">
			<button class="ps-0 btn bg-white fs_24 shadow-none SelfStorage_orange SelfStorage_tab active" id="LK-tab" data-bs-toggle="pill" data-bs-target="#LK" type="button" role="tab" aria-controls="LK" aria-selected="true">Личный кабинет</button>
			<button class="ps-0 btn bg-white fs_24 shadow-none SelfStorage_grey SelfStorage_tab" id="Rent-tab" data-bs-toggle="pill" data-bs-target="#Rent" type="button" role="tab" aria-controls="Rent" aria-selected="false">Моя аренда</button>
			<a href="./faq.html" class="btn fs_24 shadow-none text-decoration-none SelfStorage_grey SelfStorage_tab">FAQ</a>
			<a href="#" class="btn fs_24 shadow-none text-decoration-none SelfStorage_grey SelfStorage_tab">Выйти</a>
		</div>
		<div class="col-lg-9">
			<div class="card tab-content p-5">
				<div class="tab-pane fade show active" id="LK" role="tabpanel" aria-labelledby="LK-tab">
					<div class="row">
						<div class="col-12 col-sm-5 d-flex flex-column align-items-center">
							<img src="img/image10.png" class="rounded-pill mb-3" alt="">
							<h4>Екатерина Иванова</h4>
						</div>
						<div class="col-12 col-sm-7 d-flex flex-column">
							<form>
								<label class="fs_24 SelfStorage_green ms-2" for="EMAIL">E-mail</label>
								<input type="email" name="EMAIL_EDIT" id="EMAIL" class="form-control fs_24 ps-2 SelfStorage__input" value="ekatyusha89@yandex.ru" disabled>
								<label class="fs_24 SelfStorage_green ms-2" for="PHONE">Телефон</label>
								<input type="tel" name="PHONE_EDIT" id="PHONE" class="form-control fs_24 ps-2 SelfStorage__input" value="+7-909-000-00-00" disabled>
								<label class="fs_24 SelfStorage_green ms-2" for="PASSWORD">Пароль</label>
								<input type="password" name="PASSWORD_EDIT" id="PASSWORD" class="form-control fs_24 ps-2 SelfStorage__input" value="111111111" disabled>
								<button type="submit" class="btn SelfStorage_green ps-1" id="save" style="display: none">Сохранить</button>
								<a type="button" class="btn SelfStorage_orange ps-1" id="edit">Редактировать</a>
								<script>
									document.getElementById('edit').addEventListener('click', e => {
										e.preventDefault()
										document.getElementById('EMAIL').disabled = false
										document.getElementById('PHONE').disabled = false
										document.getElementById('PASSWORD').disabled = false
										document.getElementById('PASSWORD').type = 'text'
										document.getElementById('edit').style.display = 'none'
										document.getElementById('save').style.display = 'inline-block'
									})
									document.getElementById('save').addEventListener('click', () => {
										setTimeout(() => {
											document.getElementById('EMAIL').disabled = true
											document.getElementById('PHONE').disabled = true
											document.getElementById('PASSWORD').disabled = true
											document.getElementById('PASSWORD').type = 'password'
											document.getElementById('edit').style.display = 'inline-block'
											document.getElementById('save').style.display = 'none'
										}, 0)
									})
								</script>
							</form>
						</div>
					</div>
				</div>
				<div class="tab-pane fade" id="Rent" role="tabpanel" aria-labelledby="Rent-tab">
					<h1 class="fw-bold SelfStorage_green">Добрый день, Екатерина!</h1>
					<h4 class="SelfStorage_grey my-5">У вас еще нет аренды :(<br>Но вы можете арендовать свой первый бокс  по  привлекательной цене прямо сейчас</h4>
					<div><button class="btn fs_24 px-5 py-3 text-white border-8 SelfStorage__bg_orange SelfStorage__btn2_orange mb-3">Арендовать бокс</button></div>
					<a href="#" class="SelfStorage_orange">Нужна помощь?</a>
				</div>
			</div>
		</div>
	</div>
</main>
<footer class="container py-5">
	<div class="row mb-5">
		<div class="col-6 col-md-4 d-flex flex-column mb-3">
			<a href="#" class="navbar-brand">
				<img src="img/Vector.svg" alt="[]">
				<img src="img/SelfStorage.svg" alt="SelfStorage">
			</a>
			<span class="SelfStorage_green">Ежедневно: 9.00 - 21.00</span>

		</div>
		<div class="col-6 col-md-4 d-flex flex-column mb-3">
			<span class="fs_24 fw-bold SelfStorage_green">8 (800) 000-00-00</span>
			<span class="SelfStorage_green">info@selfstorage.ru</span>
		</div>
		<div class="col-6 col-md-4">
			<div class="">
				<a href="https://vk.com/devmanorg"><img src="img/VK_Compact_Logo%201.svg" alt=""></a>
				<a href="#" class="text-decoration-none">
					<svg xmlns="http://www.w3.org/2000/svg" width="53" height="53" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16">
						<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
					</svg>
				</a>
				<a href="#"><img src="img/whatsapp.svg" alt=""></a>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-6 col-md-4 d-flex flex-column">
			<p><a href="#" class="link-dark text-decoration-none">Тарифы</a></p>
			<p><a href="#" class="link-dark text-decoration-none">Рассчитать стоимость</a></p>
			<p><a href="#" class="link-dark text-decoration-none">Арендовать бокс</a></p>
		</div>
		<div class="col-6 col-md-4 d-flex flex-column">
			<p><a href="#" class="link-dark text-decoration-none">Правила хранения</a></p>
			<p><a href="#" class="link-dark text-decoration-none">Адреса складов</a></p>
			<p><a href="#" class="link-dark text-decoration-none">Отзывы</a></p>
		</div>
		<div class="col-6 col-md-4 d-flex flex-column">
			<p><a href="#" class="link-dark text-decoration-none">Политика конфиденциальности</a></p>
			<p><a href="#" class="link-dark text-decoration-none">Правовые документы</a></p>
			<p><a href="#" class="link-dark text-decoration-none">Контакты</a></p>
		</div>
		<h6 class="SelfStorage_grey text-center mt-5">© 2022 SelfStorage. Использование материалов запрещено без письменного согласия</h6>
	</div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

{% endblock %}

templates/my-rent.html
{% extends 'base.html' %}
{% load static %}
{% block script%}
<script>
	function openBox(box, end_rent) {
		let data = JSON.stringify({box: box, end_rent: end_rent});
		var xhr = new XMLHttpRequest();
		xhr.open("POST", "{% url 'api:open_box' %}", true);
		xhr.send(data);
		alert("На вашу почту отправлено сообщение с кодом доступа к помещению");
	}
</script>
{% endblock %}
{% block content %}
{% block title %}Личный кабинет{% endblock %}

<main class="container mt-header">
	<div class="row" role="tablist">
		<div class="col-lg-3 d-flex flex-column nav nav-pills">
			<button class="ps-0 btn bg-white fs_24 shadow-none SelfStorage_orange SelfStorage_tab active" id="LK-tab" data-bs-toggle="pill" data-bs-target="#LK" type="button" role="tab" aria-controls="LK" aria-selected="true">Личный кабинет</button>
			<button class="ps-0 btn bg-white fs_24 shadow-none SelfStorage_grey SelfStorage_tab" id="Rent-tab" data-bs-toggle="pill" data-bs-target="#Rent" type="button" role="tab" aria-controls="Rent" aria-selected="false">Моя аренда</button>
			<a href="{% url 'faq' %}" class="btn fs_24 shadow-none text-decoration-none SelfStorage_grey SelfStorage_tab">FAQ</a>
			<a href="{% url 'logout' %}" class="btn fs_24 shadow-none text-decoration-none SelfStorage_grey SelfStorage_tab">Выйти</a>
		</div>
		<div class="col-lg-9">
		{% if user.is_authenticated %}
			<div class="card tab-content p-5">
				<div class="tab-pane fade show active" id="LK" role="tabpanel" aria-labelledby="LK-tab">
					<div class="row">
						<div class="col-12 col-sm-5 d-flex flex-column align-items-center">
							<img src="{% static 'img/image102.png' %}" class="rounded-pill mb-3" alt="">
							<h4>{{user.email}}</h4>
						</div>
						<div class="col-12 col-sm-7 d-flex flex-column">
							<form action="/account/" method="post">
								{% csrf_token %}
								<label class="fs_24 SelfStorage_green ms-2" for="EMAIL">E-mail</label>
								<input type="email" name="EMAIL_EDIT" id="EMAIL" class="form-control fs_24 ps-2 SelfStorage__input" value="{{user.email}}" disabled>
								<label class="fs_24 SelfStorage_green ms-2" for="PHONE">Телефон</label>
								<input type="tel" name="PHONE_EDIT" id="PHONE" class="form-control fs_24 ps-2 SelfStorage__input" value="{{user.phonenumber}}" disabled>
								<label class="fs_24 SelfStorage_green ms-2" for="PASSWORD">Пароль</label>
								<input type="password" name="PASSWORD_EDIT" id="PASSWORD" class="form-control fs_24 ps-2 SelfStorage__input" value="{{user.password}}" disabled>

								<a class="btn SelfStorage_orange ps-1" id="edit">Редактировать</a>
								<button type="submit" class="btn SelfStorage_green ps-1" id="save" style="display: none">Сохранить</button>
								<script>
									document.getElementById('edit').addEventListener('click', e => {
										e.preventDefault()
										document.getElementById('EMAIL').disabled = false
										document.getElementById('PHONE').disabled = false

										document.getElementById('edit').style.display = 'none'
										document.getElementById('save').style.display = 'inline-block'
									})
									document.getElementById('save').addEventListener('click', () => {
										setTimeout(() => {
											document.getElementById('EMAIL').disabled = true
											document.getElementById('PHONE').disabled = true

											document.getElementById('edit').style.display = 'inline-block'
											document.getElementById('save').style.display = 'none'
										}, 0)
									})
								</script>
							</form>
						</div>
					</div>
				</div>
			{% if not user_boxes %}
				<div class="tab-pane fade" id="Rent" role="tabpanel" aria-labelledby="Rent-tab">
					<h1 class="fw-bold SelfStorage_green">Добрый день, {{user.email}}!</h1>
					<h4 class="SelfStorage_grey my-5">У вас еще нет аренды :(<br>Но вы можете арендовать свой первый бокс  по  привлекательной цене прямо сейчас</h4>
					<div><a href="{% url 'boxes' %}" class="btn fs_24 px-5 py-3 text-white border-8 SelfStorage__bg_orange SelfStorage__btn2_orange mb-3">Арендовать бокс</a></div>
					<a href="#" class="SelfStorage_orange">Нужна помощь?</a>
				</div>
			{% else %}
				<div class="tab-pane fade" id="Rent" role="tabpanel" aria-labelledby="Rent-tab">
					<h1 class="fw-bold SelfStorage_green mb-5">Добрый день, <br>{{user.email}}</h1>
					<a href="#" class="SelfStorage_orange">История аренды</a>
					<br><br>
				{% for box in user_boxes %}
					{% if box.order.get_delay <= 5 %}
					<h4 class="SelfStorage_grey my-3">Срок Вашей аренды подходит к концу :(<br>Вы можете продлить аренду или забрать вещи до {{ box.order.end_current_rent|date:"j.m.Y" }} включительно.</h4>
					{% else %}
					{% endif %}
					<div class="mb-5">
						<h4 class="SelfStorage_green">Cклад {{box.storage.city}}</h4>
						<h4>{{box.storage}}</h4>
						<h4 class="SelfStorage_green">Мой бокс</h4>
						<h4>№{{box.number}}</h4>
						<h4 class="SelfStorage_green">Срок аренды</h4>
						<h4>{{ box.order.start_current_rent|date:"j.m.Y" }} - {{ box.order.end_current_rent|date:"j.m.Y" }}</h4>
						<div><a class="btn fs_24 px-5 py-3 text-white border-8 SelfStorage__bg_green SelfStorage__btn2_green mb-3" href="{% url 'order_details' product_number=box.number %}?prolong=1">Продлить аренду</a></div>
						<div><button onclick= "openBox('{{box}}', false)", class="btn fs_24 px-5 py-3 text-white border-8 SelfStorage__bg_orange SelfStorage__btn2_orange mb-3">Открыть бокс</button></div>
						<div><button onclick= "openBox('{{box}}', true)", class="btn fs_24 px-5 py-3 text-white border-8 SelfStorage__bg_orange SelfStorage__btn2_orange mb-3">Завершить аренду</button></div>
					</div>
				{% endfor %}
						<a href="#" class="SelfStorage_orange">Нужна помощь?</a>
				</div>
			{% endif %}
			</div>
		{% else %}
		<h1>Зарегистрируйтесь или войдите</h1>
		{% endif %}
		</div>
	</div>
</main>
<footer class="container py-5">
	<div class="row mb-5">
		<div class="col-6 col-md-4 d-flex flex-column mb-3">
			<a href="{% url 'index' %}" class="navbar-brand">
				<img src="{% static 'img/Vector.svg' %}" alt="[]">
				<img src="{% static 'img/SelfStorage.svg' %}" alt="SelfStorage">
			</a>
			<span class="SelfStorage_green">Ежедневно: 9.00 - 21.00</span>

		</div>
		<div class="col-6 col-md-4 d-flex flex-column mb-3">
			<span class="fs_24 fw-bold SelfStorage_green">8 (800) 000-00-00</span>
			<span class="SelfStorage_green">info@selfstorage.ru</span>
		</div>
		<div class="col-6 col-md-4">
			<div class="">
				<a href="https://vk.com/devmanorg"><img src="{% static 'img/VK_Compact_Logo%201.svg' %}" alt=""></a>
				<a href="#" class="text-decoration-none">
					<svg xmlns="http://www.w3.org/2000/svg" width="53" height="53" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16">
						<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
					</svg>
				</a>
				<a href="#"><img src="{% static 'img/whatsapp.svg' %}" alt=""></a>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-6 col-md-4 d-flex flex-column">
			<p><a href="#" class="link-dark text-decoration-none">Тарифы</a></p>
			<p><a href="{% url 'index' %}#calculate" class="link-dark text-decoration-none">Рассчитать стоимость</a></p>
			<p><a href="#" class="link-dark text-decoration-none">Арендовать бокс</a></p>
		</div>
		<div class="col-6 col-md-4 d-flex flex-column">
			<p><a href="{% url 'faq' %}" class="link-dark text-decoration-none">Правила хранения</a></p>
			<p><a href="#" class="link-dark text-decoration-none">Адреса складов</a></p>
			<p><a href="#" class="link-dark text-decoration-none">Отзывы</a></p>
		</div>
		<div class="col-6 col-md-4 d-flex flex-column">
			<p><a href="#" class="link-dark text-decoration-none">Политика конфиденциальности</a></p>
			<p><a href="#" class="link-dark text-decoration-none">Правовые документы</a></p>
			<p><a href="#" class="link-dark text-decoration-none">Контакты</a></p>
		</div>
		<h6 class="SelfStorage_grey text-center mt-5">© 2022 SelfStorage. Использование материалов запрещено без письменного согласия</h6>
	</div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

{% endblock %}